### ISSUE TITLE
Error when training the model

### ISSUE THREAD

**Issue by francismontalbo** [anki-xyz/bagls#3]
ValueError: the input array must have size 3 along `channel_axis`, got (512, 256) 

it is raising this error. Hoping for your help. Thank you!

**Comment by gomezzz** [comment]
Hi! Depending on where that error is thrown you either need a channel dimension (above sounds like gray scale data), so you would need to make it (512,256,1) or if the function you are calling is expecting a batch of images you lacking a leading dimension, thus (1,512,256) if you really want to give it one image or (N,512,256) for N images.

You can you use a function such as [expand_dims](https://www.tensorflow.org/api_docs/python/tf/expand_dims) to insert dimensions.

Hope it helps, otherwise would need to know more about your data and where the error occurs.

**Comment by francismontalbo** [comment]
Thank you for the reply. I managed to create a custom data generator to use the dataset. I already trained and benchmarked several models. May I know, a recent paper or work that have done such for the BAGLS dataset?

**Comment by paxbo** [comment]
Hi, I get the same error when trying to train a model with the files loaded from kaggel. 
Which version of  imageio and skimage did you use? 

`RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "***\.conda\envs\bagls_env\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "***\.conda\envs\bagls_env\lib\site-packages\keras\utils\data_utils.py", line 406, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "***\BAGLS\bagls\Utils\DataGenerator.py", line 87, in __getitem__
    Y_id)), (self.height, self.width)), -1.0, 1.0)) / 255
  File "***\lib\site-packages\skimage\_shared\utils.py", line 394, in fixed_func
    return func(*args, **kwargs)
  File "***\.conda\envs\bagls_env\lib\site-packages\skimage\color\colorconv.py", line 875, in rgb2gray
    rgb = _prepare_colorarray(rgb)
  File "***\.conda\envs\bagls_env\lib\site-packages\skimage\color\colorconv.py", line 140, in _prepare_colorarray
    raise ValueError(msg)
ValueError: the input array must have size 3 along channel_axis, got (512, 256)
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_46340\2513892030.py in <module>
     57             max_queue_size=32,
     58             # Custom Callbacks
---> 59             callbacks=callbacks)

~\.conda\envs\bagls_env\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\.conda\envs\bagls_env\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1656             use_multiprocessing=use_multiprocessing,
   1657             shuffle=shuffle,
-> 1658             initial_epoch=initial_epoch)
   1659 
   1660     @interfaces.legacy_generator_methods_support

~\.conda\envs\bagls_env\lib\site-packages\keras\engine\training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    179             batch_index = 0
    180             while steps_done < steps_per_epoch:
--> 181                 generator_output = next(output_generator)
    182 
    183                 if not hasattr(generator_output, '__len__'):

~\.conda\envs\bagls_env\lib\site-packages\keras\utils\data_utils.py in get(self)
    614         except Exception:
    615             self.stop()
--> 616             six.reraise(*sys.exc_info())
    617 
    618 

~\.conda\envs\bagls_env\lib\site-packages\six.py in reraise(tp, value, tb)
    717             if value.__traceback__ is not tb:
    718                 raise value.with_traceback(tb)
--> 719             raise value
    720         finally:
    721             value = None

~\.conda\envs\bagls_env\lib\site-packages\keras\utils\data_utils.py in get(self)
    601                 try:
    602                     future = self.queue.get(block=True)
--> 603                     inputs = future.get(timeout=30)
    604                     self.queue.task_done()
    605                 except mp.TimeoutError:

~\.conda\envs\bagls_env\lib\multiprocessing\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):´

ValueError: the input array must have size 3 along `channel_axis`, got (512, 256)`

**Comment by anki-xyz** [comment]
You need to ensure, that you have either one or three (RGB) channels, i.e. (512,256,1) or (512,256,3), even though the image is maybe grayscale to satisfy scikit-image.

You can expand the input to `(512, 256, 1)` by passing the variable, let's say `X`, in this way `X[...,None]` to the function that raises the issue. (512, 256) has height and width pixels, but only a single channel.
